name: ImagicalMail
author: remote_vase
version: 1.0.0dev#1
api: [1.0.0, 2.0.0, 3.0.0]
main: ImagicalMail\ImagicalLoader\Loader
load: POSTWORLD
commands:
  mail see:
    usage: /mail see
    description: See all of your ImagicalMail
  mail clear:
    usage: /mail clear
    description: Clear your ImagicalInbox
  mail send:
    usage: /mail send
    description: Send an ImagicalMail to someones ImagicalInbox
